// Built-in supplement directory for search-as-you-type suggestions.
// Local data: instant, offline, nothing leaves the browser.
// These are common product names with generic serving descriptors as editable
// starting text — not recommendations and not dosage advice. The user always
// edits before saving; the in-app disclaimer still applies.
export const SUPPLEMENT_DIRECTORY = [
  { name: "Multivitamin", serving: "1 tablet", time: "Morning" },
  { name: "Vitamin A", serving: "1 softgel", time: "Morning" },
  { name: "Vitamin C", serving: "1 tablet", time: "Morning" },
  { name: "Vitamin D3", serving: "1 softgel", time: "Morning" },
  { name: "Vitamin D3 + K2", serving: "1 softgel", time: "Morning" },
  { name: "Vitamin E", serving: "1 softgel", time: "Morning" },
  { name: "Vitamin K2 (MK-7)", serving: "1 capsule", time: "Morning" },
  { name: "B-Complex", serving: "1 tablet", time: "Morning" },
  { name: "Vitamin B12", serving: "1 tablet", time: "Morning" },
  { name: "Thiamine (B1)", serving: "1 tablet", time: "Morning" },
  { name: "Riboflavin (B2)", serving: "1 tablet", time: "Morning" },
  { name: "Niacin (B3)", serving: "1 capsule", time: "Morning" },
  { name: "Pantothenic Acid (B5)", serving: "1 capsule", time: "Morning" },
  { name: "Vitamin B6", serving: "1 tablet", time: "Morning" },
  { name: "Biotin (B7)", serving: "1 tablet", time: "Morning" },
  { name: "Folate", serving: "1 tablet", time: "Morning" },
  { name: "Calcium", serving: "1 tablet", time: "Evening" },
  { name: "Magnesium Glycinate", serving: "1 capsule", time: "Evening" },
  { name: "Magnesium Citrate", serving: "1 capsule", time: "Evening" },
  { name: "Magnesium", serving: "1 capsule", time: "Evening" },
  { name: "Zinc Picolinate", serving: "1 capsule", time: "Evening" },
  { name: "Zinc", serving: "1 tablet", time: "Evening" },
  { name: "Iron", serving: "1 tablet", time: "Morning" },
  { name: "Potassium", serving: "1 tablet", time: "Morning" },
  { name: "Selenium", serving: "1 capsule", time: "Morning" },
  { name: "Iodine", serving: "1 drop", time: "Morning" },
  { name: "Copper", serving: "1 tablet", time: "Morning" },
  { name: "Manganese", serving: "1 tablet", time: "Morning" },
  { name: "Chromium", serving: "1 capsule", time: "Morning" },
  { name: "Boron", serving: "1 capsule", time: "Morning" },
  { name: "Trace Minerals", serving: "1 dropper", time: "Morning" },
  { name: "Omega-3 Fish Oil", serving: "2 softgels", time: "Morning" },
  { name: "Krill Oil", serving: "1 softgel", time: "Morning" },
  { name: "Cod Liver Oil", serving: "1 softgel", time: "Morning" },
  { name: "Algae Omega-3", serving: "1 softgel", time: "Morning" },
  { name: "Flaxseed Oil", serving: "1 softgel", time: "Morning" },
  { name: "Whey Protein", serving: "1 scoop", time: "Anytime" },
  { name: "Plant Protein", serving: "1 scoop", time: "Anytime" },
  { name: "Collagen Peptides", serving: "1 scoop", time: "Morning" },
  { name: "Creatine Monohydrate", serving: "1 scoop", time: "Anytime" },
  { name: "L-Carnitine", serving: "1 capsule", time: "Morning" },
  { name: "BCAAs", serving: "1 scoop", time: "Anytime" },
  { name: "L-Glutamine", serving: "1 scoop", time: "Anytime" },
  { name: "Beta-Alanine", serving: "1 scoop", time: "Anytime" },
  { name: "Taurine", serving: "1 capsule", time: "Anytime" },
  { name: "Probiotic", serving: "1 capsule", time: "Morning" },
  { name: "Prebiotic Fiber", serving: "1 scoop", time: "Morning" },
  { name: "Psyllium Husk", serving: "1 capsule", time: "Morning" },
  { name: "Digestive Enzymes", serving: "1 capsule", time: "Anytime" },
  { name: "Ginger", serving: "1 capsule", time: "Anytime" },
  { name: "Greens Powder", serving: "1 scoop", time: "Morning" },
  { name: "Spirulina", serving: "1 tablet", time: "Morning" },
  { name: "Chlorella", serving: "1 tablet", time: "Morning" },
  { name: "Wheatgrass", serving: "1 tablet", time: "Morning" },
  { name: "Beetroot Powder", serving: "1 scoop", time: "Morning" },
  { name: "Melatonin", serving: "1 tablet", time: "Evening" },
  { name: "L-Theanine", serving: "1 capsule", time: "Evening" },
  { name: "Ashwagandha", serving: "1 capsule", time: "Evening" },
  { name: "Valerian Root", serving: "1 capsule", time: "Evening" },
  { name: "Chamomile", serving: "1 capsule", time: "Evening" },
  { name: "Caffeine", serving: "1 tablet", time: "Morning" },
  { name: "L-Tyrosine", serving: "1 capsule", time: "Morning" },
  { name: "Ginkgo Biloba", serving: "1 capsule", time: "Morning" },
  { name: "Bacopa Monnieri", serving: "1 capsule", time: "Morning" },
  { name: "Rhodiola Rosea", serving: "1 capsule", time: "Morning" },
  { name: "CoQ10", serving: "1 softgel", time: "Morning" },
  { name: "Garlic", serving: "1 softgel", time: "Evening" },
  { name: "Turmeric Curcumin", serving: "1 capsule", time: "Evening" },
  { name: "Glucosamine Chondroitin", serving: "1 tablet", time: "Morning" },
  { name: "MSM", serving: "1 capsule", time: "Morning" },
  { name: "Hyaluronic Acid", serving: "1 capsule", time: "Morning" },
  { name: "Saw Palmetto", serving: "1 softgel", time: "Evening" },
  { name: "Milk Thistle", serving: "1 capsule", time: "Evening" },
  { name: "Echinacea", serving: "1 capsule", time: "Morning" },
  { name: "Elderberry", serving: "1 gummy", time: "Morning" },
  { name: "Vitamin C + Zinc", serving: "1 tablet", time: "Morning" },
  { name: "Apple Cider Vinegar", serving: "1 gummy", time: "Morning" },
  { name: "Biotin Gummies", serving: "2 gummies", time: "Morning" },
  { name: "Electrolytes", serving: "1 stick", time: "Anytime" },
  { name: "Fiber Gummies", serving: "2 gummies", time: "Morning" },
];

export function searchSupplements(query, limit = 8) {
  const q = String(query || "").trim().toLowerCase();
  if (q.length < 2) return [];
  return SUPPLEMENT_DIRECTORY.filter((item) =>
    item.name.toLowerCase().includes(q),
  ).slice(0, limit);
}
